### ISSUE TITLE
Cannot enable solarized-dark

### ISSUE THREAD

**Issue by ramLlama** [sellout/emacs-color-theme-solarized#142]
When I run emacs terminal-only as `env TERM=xterm-16color emacs -nw`, I start in the solarized-light theme but cannot switch to solarized-dark. Here is an output of when I try to do so in the scratch buffer

    (frame-parameter nil 'background-mode)
    light
    (set-frame-parameter nil 'background-mode 'dark)
    nil
    (frame-parameter nil 'background-mode)
    dark
    (enable-theme 'solarized)
    nil
    ;; Nothing happens!
    (frame-parameter nil 'background-mode)
    light
    ;; It changed back?!

The only line I have to load solarized in my init.el is `(load-theme 'solarized t)`. Also note that this issue does *not* occur in GUI/X mode!

My System:
* M-x version output: `GNU Emacs 25.0.50.1 (x86_64-unknown-linux-gnu, GTK+ Version 3.4.2) of 2014-10-17 on <hostname removed>`
* I am using Emacs 24 Themes
* `(display-color-cells)` output: 16
* Terminal: gnome-terminal
* Does the problem occur in GUI mode?: No

**Comment by sellout** [comment]
Thanks for the great bug report!

Unfortunately, I don’t know why this happens. Someone reported the same behavior in #emacs on IRC a few days ago, and they said that it worked properly if they did `emacs -Q` and then manually loaded the theme, but I never heard back as to whether they deduced where the problem was. That gives some indication that the problem is not in solarized itself, but regardless, I’d at least like to know where it’s happening so I can maybe fix the offending package or at least warn other users.

**Comment by crsmithdev** [comment]
Same issue.

version: ```GNU Emacs 24.4.1 (x86_64-apple-darwin14.0.0) of 2014-11-06 on <...>```
terminal: iterm2

...works fine w/ emacs for osx.

**Comment by crsmithdev** [comment]
Actually it *does* occur if I try to open a new window for Emacs for OSX:  the second one always loads w/ the light theme.

**Comment by qinix** [comment]
Same issue.

**Comment by darfink** [comment]
Same issue here as well (GNU Emacs 24.4.1, OS X, iTerm 2)

**Comment by pyr** [comment]
On archlinux and emacs 24.4.1 I can confirm the behavior.

**Comment by pyr** [comment]
After some digging, it looks as if the issue is directly related to `load-theme`, even without solarized the `background-mode` frame parameter gets reset. It'd be interesting to know if this is true for users of previous emacs versions as well to try and pinpoint when this happened.

**Comment by pyr** [comment]
Alright, after more digging I've reached a satisfying solution. The culprit is the recent way of handling terminal settings in emacs. You'll have to not only adjust your frame parameters but also your terminal parameters.

A good way of approaching this could be (assuming `mode` contains either 'light or 'dark)

```elisp
   (set-frame-parameter nil 'background-mode mode)
   (when (not (display-graphic-p (selected-frame)))
      (set-terminal-parameter nil 'background-mode mode))
   (enable-theme 'solarized)
```
  

```

**Comment by vsbuffalo** [comment]
Same issue. @pyr's solution sadly doesn't seem to work.

    $ emacs --version
    GNU Emacs 24.3.50.1

**Comment by fredcy** [comment]
The fix by @pyr works for me. Thanks.
Mac OS X: GNU Emacs 24.4.1
RHEL6:  GNU Emacs 24.4.50.1
cygwin: GNU Emacs 24.4.1
mingw: GNU Emacs 24.3.1

**Comment by finecrawler** [comment]
The fix by @pyr works for me. Thanks. 
Iterm2 on Mac OS.

**Comment by sellout** [comment]
@ramLlama Since you’re the creator, I defer to you – is this ticket suitably resolved?

**Comment by ramLlama** [comment]
Ah, its been a while since I checked this out. I need to sleep now =) but I
will test tomorrow and report back.

**Comment by sellout** [comment]
I’m going to assume this is fixed (it _should_ be). But feel free to reopen if it’s not working for you.
