### ISSUE TITLE
Eww not using solarized

### ISSUE THREAD

**Issue by ephexeve** [sellout/emacs-color-theme-solarized#156]
Does solarized also supports the ```eww```?
When using it, apparently I get the solarized-light theme -> https://imgur.com/AcNtleH

Any idea how to fix this?

**Comment by sellout** [comment]
I’m pretty sure this is because of EWW using colors defined by the CSS on Ycombinator. If you go to a different site (say, github.com), you’ll get solarized colors, since they don’t override the defaults.

I’m going to mark this as closed, but feel free to reopen it if you don’t think Solarized is actually behaving.

**Comment by ephexeve** [comment]
Yup, I just checked it, you are right. I migrated to emacs w3m, this works like a charm. 

Thanks
