### ISSUE TITLE
Emacs' version of solarized uses wrong colors for highlighting elements.

### ISSUE THREAD

**Issue by axg-ux** [sellout/emacs-color-theme-solarized#169]
Compared with the stock vim version it is easy to see how most elements of syntax use "wrong colors" at least not the default spec. Why is that the behavior of the official emacs solarized theme?

In the screenshot attached, on the left is seen emacs using rather strangle highlighting colors for some config in haskell, compared to the right side, where a vim version of the same document is launched.
Is there a reason for such behavior? Can it be fixed or reversed?

![2015-08-28-232155_1917x1062_scrot](https://cloud.githubusercontent.com/assets/8572801/9560756/8e34b1d0-4ddb-11e5-906b-98be000ac871.png)

**Comment by sellout** [comment]
Here’s the high-level explanation:

https://github.com/sellout/emacs-color-theme-solarized/wiki/Why-doesn't-it-look-like-the-VIM-version%3F

I’m happy to accept PRs (or issues) for specific things that are wrong with the theme, but I expect many of these differences are due to the mode or face definitions.

**Comment by axg-ux** [comment]
I see so it is the specific major modes that decide what colors to use for highlighting specific syntax elements (or faces as you seem to refer to them in emacs). Therefore in order to change the way some piece of code in a specific language looks, I could go into the major mode's syntax highlighting specification and play with it in there. Am I seeing this through right?
