### ISSUE TITLE
solarized changes org-mode faces.

### ISSUE THREAD

**Issue by codersam88** [sellout/emacs-color-theme-solarized#171]
While using solarized theme I observe that it changes faces of org-mode. The new faces change the size of the text. The final effect is not at all good. Please fix it
![orgmode](https://cloud.githubusercontent.com/assets/1143331/10014501/3f57461c-6137-11e5-9e28-e66fda1fe950.png)

**Comment by gugek** [comment]
Do you have `variable-pitch-mode` enabled somewhere? What you are seeing shouldn't be the default.

The headings colors were updated ba6b17ba9b5e69568f270434b72365434ecf2b10 to inherit directly from outline mode.

Maybe you are seeing an upstream effect from either org-mode, a particular customization like `variable-pitch-mode` or you aren't using a current solarized color theme since the colors aren't the same as what is being defined now.

    (outline-1 (,@fg-blue))
    (outline-2 (,@fg-cyan))
    (outline-3 (,@fg-yellow))
    (outline-4 (,@fg-red))
    (outline-5 (,@fg-base0))
    (outline-6 (,@fg-base01))
    (outline-7 (,@fg-orange))
    (outline-8 (,@fg-violet))

![org-solarized-light](https://cloud.githubusercontent.com/assets/223778/10018787/71085ffa-6107-11e5-97e8-5a5540797bf2.PNG)

**Comment by sellout** [comment]
@codersam88 You seem to be using bbatsov/solarized-emacs, not this version.

**Comment by sellout** [comment]
Oh, and here’s a reference to the org-mode stuff in that repo – you can see the colors match, and `variable-pitch-mode` is used, etc.

**Comment by sellout** [comment]
https://github.com/bbatsov/solarized-emacs/blob/master/solarized.el#L1588

**Comment by codersam88** [comment]
(setq solarized-scale-org-headlines nil) this solved my problem

**Comment by codersam88** [comment]
Thank you for the info. Sorry for troubling you
