### ISSUE TITLE
Many "Unable to load color" messages when loading

### ISSUE THREAD

**Issue by fredcy** [sellout/emacs-color-theme-solarized#175]
My emacs \*Messages* buffer has many messages like this when loading the solarized theme.
```
Unable to load color "brightyellow" [8 times]
Unable to load color "brightwhite" [2 times]
Unable to load color "brightyellow" [2 times]
Unable to load color "brightwhite"
Unable to load color "brightyellow"
```
These happen only when running in an iterm2 terminal, not when running Emacs.app. I installed emacs with homebrew on Mac OS X 10.10.5.

* emacs version:  GNU Emacs 24.5.1 (x86_64-apple-darwin14.4.0, NS apple-appkit-1348.17) of 2015-08-18 on rainier.itnet.imsa.edu
* I think I'm using the native Emacs 24 theme system. I don't explicitly load `color-theme` anywhere.
* I see the "unable to load color" message for these faces: brightyellow, brightblue, brightblack [?], brightgreen, brightcyan, and brightwhite.
* When I run `M-: (display-color-cells)` I get "256 (#o400, #x100, ?Ā)".
* I'm using iTerm2, build 2.1.4. I loaded color presets for solarized into it long ago. The bright yellow value shows in iTerm prefs as a dark gray.
* The problem does not arise in the GUI version of Emacs (Emacs.app).
* I'm using the latest commit of emacs-color-theme-solarized, 412713a.

Here is the init code I'm using:

``` lisp
(add-to-list 'custom-theme-load-path "~/.emacs.d/emacs-color-theme-solarized")
(load-theme 'solarized t)

(defun setup-background (frame)
  (let* ((background (if (display-graphic-p frame) 'light 'dark)))
    (message "setup-background(%s): %s" frame background)
    (set-frame-parameter frame 'background-mode background)
    (set-terminal-parameter (frame-terminal frame) 'background-mode background))
  (enable-theme 'solarized))

;;; Set up background of initial frame
(mapc 'setup-background (visible-frame-list))
```

**Comment by lifepillar** [comment]
I have exactly the same problem, just with Terminal.app instead of iTerm. In fact, I am using `color-theme-solarized` from MELPA, which I believe is the same as this project. I have tried to require `color-theme` before loading the theme, but that does not change anything. I have installed Emacs with Homebrew (`emacs-mac` formula from the `railwaycat/emacsmacport` tap).

It is worth mentioning that, despite those errors, the theme seems to look ok even in the terminal (but I have not tested it much).

**Comment by sellout** [comment]
Try setting `solarized-termcolors` to 256 rather than (the default) 16. I should try to make this variable smarter – some 256-color terms actually do support the named colors in addition to the standard 256, others don’t. And the named colors are more correct if they’re available.

**Comment by fredcy** [comment]
I added `(customize-set-variable 'solarized-termcolors 256)` and now I no longer see any of the "Unable to load color" messages, so that does the trick. Thanks.

(I thought I had tried that before. Perhaps I was not setting `solarized-termcolors` the right way or in the right place.)

**Comment by jasonm23** [comment]
Just for reference this error seems to be sent whether the terminal recognizes the color name or not.

The reason setting `solarized-termcolors` to **256** solves the problem is because the color values used are hex color strings instead of color names.

As long as the target terminal recognizes a color name, it will be set correctly. (the Emacs error message will still show of course, but it's a false report.)
