### ISSUE TITLE
disable changing font weight

### ISSUE THREAD

**Issue by s9gf4ult** [sellout/emacs-color-theme-solarized#97]
When I load solarized theme it redefines many faces and font weight as well. I would like in light theme my Terminus would `bold`, but solarized force it to be `medium`. How to change ?

**Comment by sellout** [comment]
@s9gf4ult You can `customize-theme solarized` and override those settings.

@seh that might also be nicer than the `eval-after-load` stuff, since it’s local to the theme.

The original Solarized theme for Vim is very explicit about controlling all the font properties, not just colors. One of the goals of this project is to maintain as much similarity to the Vim version as possible.

There are also a couple customizable variables, like `solarized-bold`, but if you set that to `nil`, then it will force medium weight, not just ignore the bold settings.
